config/routes.rb
require 'api_constraints'
Nuryl::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,path_names: {sign_up: "registrations"} ,controllers: {sessions: 'sessions', passwords: 'passwords'}
  resources :users, only: [:show, :edit, :update ]
  # Api definition
  devise_scope :user do
    root to: "sessions#new"
    match 'api/v1/user_registration' => 'api/v1/registrations#create', :via => :post
    match 'api/v1/help' => 'api/v1/helps#create', :via => :post
    match '/api/v1/users/forget_password' => 'api/v1/passwords#create', :via => :post
    match '/api/v1/users/change_password' => 'api/v1/passwords#update_password_api', :via => :put
    match 'user_registration' => 'api/v1/registrations#new', :via => :get
    match 'registration' => 'registrations#create', :via => :post
    match  'subscribe' => 'transactions#new_subscription', :via => :get
    match 'edit_password' => 'devise/passwords#edit', :via => :get
    match 'update_password/:id' => 'devise/passwords#update', :via => :put
  end


  namespace :api, defaults: { format: :json },
             path: '/api'  do
    scope module: :v1 , path: '/v1',
          constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
      devise_for :users
      resources :users ,only: [] do
        collection do
          get 'course_content'
          get 'validate_unique_email'
          get 'courses/:course_id/:content_type/:content_id' => 'users#get_content'
          post 'courses/:course_id' => 'users#player_usage_status'
          get 'usage_statics' => 'users#send_usage_statics_info'
          get 'edit_profile' => 'users#edit_profile'
          post 'update_profile' => 'users#update_profile'
          get 'subscription_mail' => 'users#send_subscription_mail'
          get 'get_urls' => 'users#get_urls'
        end
      end
      resources :transactions, only: [:create] do
        collection do
          post 'subscripe' => 'transactions#create'
          get 'subscription_type' => 'transactions#get_subscription_type'
          get 'subscription_status' => 'transactions#subscription_status'
          get 'subscription_amount' => 'transactions#get_subscription_amount'
          post 'change_subscription_plan' => 'transactions#change_plan'
          post 'new_subscription' => 'transactions#new_subscription'
          post 'cancel_subscription' => 'transactions#cancel_subscription'
          post 'webhook' => 'transactions#webhook'
          put 'update_card' => 'transactions#update_card'
        end
      end
    end
  end

  resources :transactions ,only: [:new] do
    collection do
      get 'change_card_details' => 'transactions#change_card_details'
      put 'update_card' => 'transactions#update_card_details'
      post 'paypal_transaction_process' => 'transactions#paypal_transaction_process'
      post 'subscripe' => 'transactions#create'
      post 'paypal_hook' => 'transactions#paypal_hook'
    end
  end



  resources :childrens ,only: [:new, :create] do

  end


end

app/controllers/api/v1/transactions_controller.rb
class  Api::V1::TransactionsController < ApplicationController
  include UserCommonMethodControllerConcern
  include TransactionCommonMethodControllerConcern
  skip_before_filter :is_device_id?, :only => [:webhook]
  skip_before_filter :authenticate_scope!, :only => [:webhook]
  skip_before_filter :authenticate_user_from_token!, :only => [:webhook]
  skip_before_filter :authenticate_device, :only => [:webhook]
  respond_to :json

  def create
      return render status: 200, :json=> {:success => false, data: [t('active_subscription')] } if current_user.has_account? && current_user.active_subscription?
      return render status: 200, :json=> {:success => false, data: [t('no_payment_gateway')] } if params[:payment_gateway_type].blank?
      service_class = payment_service
      return render status: 200, :json=> {:success => false, data: [t('invalid_payment_gateway')] } if service_class.nil?
      return render status: 200, :json=> {:success => false, data: [t('invalid_plan')] } if plan_with_name.nil?
      unless  method_exist?(service_class,:create_payment_service )
        return render status: 200, :json=> {:success => false, data: [t('no_feature_for_this_service',
                                                                        service: service_class, method: 'create payment')] }
      end
      begin
        #redirecting corresponding payment gateway service
        service_class = payment_service
        service_class.new.create_payment_service(current_user, params)
      rescue service_class::PaymentError  => e
        return render status: 200, :json=> {:success => false, data: e.message }
      end
      return render status: 201, :json=> {:success => true, data: 'Account created' }

  end

  def get_subscription_amount
    plan = plan_with_name
    if plan.nil?
      return render status: 200, :json=> {:success => false, data: [t('invalid_plan')] }
    else
      return render status: 200, :json=> {:success => true, data: {amount: plan.amount} }
    end
  end

  def change_plan
      return render status: 200, :json=> {:success => false, data: [t('no_account')] } unless current_user.has_account?
      return render status: 200, :json=> {:success => false, data: [t('no_active_subscription')] } unless  current_user.active_subscription?
      return render status: 200, :json=> {:success => false, data: [t('no_payment_gateway')] } if params[:payment_gateway_type].blank?
      service_class = payment_service
      return render status: 200, :json=> {:success => false, data: [t('invalid_payment_gateway')] } if service_class.nil?
      return render status: 200, :json=> {:success => false, data: [t('invalid_plan')] } if plan_with_name.nil?
      unless  method_exist?(service_class,:change_plan_service )
        return render status: 200, :json=> {:success => false, data: [t('no_feature_for_this_service',
                                                                        service: service_class, method: 'change plan')] }
      end
      begin
        #redirecting corresponding payment gateway service
        service_class = payment_service
        service_class.new.change_plan_service(current_user, params)
      rescue service_class::PaymentError  => e
        return render status: 200, :json=> {:success => false, data: e.message }
      end
      return render status: 201, :json=> {:success => true, data: {data: "Plan updated to " + params[:subscription_type] } }
  end

  def new_subscription
    return render status: 200, :json=> {:success => false, data: [t('no_account')] } unless current_user.has_account?
    return render status: 200, :json=> {:success => false, data: [t('no_payment_gateway')] } if params[:payment_gateway_type].blank?
    service_class = payment_service
    return render status: 200, :json=> {:success => false, data: [t('invalid_payment_gateway')] } if service_class.nil?
    return render status: 200, :json=> {:success => false, data: [t('invalid_plan')] } if plan_with_name.nil?
    unless  method_exist?(service_class,:new_subscription_service )
      return render status: 200, :json=> {:success => false, data: [t('no_feature_for_this_service',
                                                                      service: service_class, method: 'new subscription')] }
    end
    begin
      #redirecting corresponding payment gateway service
      service_class = payment_service
      service_class.new.new_subscription_service(current_user, params)
    rescue service_class::PaymentError  => e
      return render status: 200, :json=> {:success => false, data: e.message }
    end
    return render status: 201, :json=> {:success => true, data: {data: "New subscription added" } }
  end

  def cancel_subscription
    return render status: 200, :json=> {:success => false, data: [t('no_account')] } unless current_user.has_account?
    return render status: 200, :json=> {:success => false, data: [t('no_active_subscription')] } unless  current_user.active_subscription?
    return render status: 200, :json=> {:success => false, data: [t('no_payment_gateway')] } if params[:payment_gateway_type].blank?
    service_class = payment_service
    return render status: 200, :json=> {:success => false, data: [t('invalid_payment_gateway')] } if service_class.nil?
    unless  method_exist?(service_class,:cancel_subscription_service )
      return render status: 200, :json=> {:success => false, data: [t('no_feature_for_this_service',
                                                                      service: service_class, method: 'cancel subscription')] }
    end
    begin
      #redirecting corresponding payment gateway service
      service_class = payment_service
      service_class.new.cancel_subscription_service(current_user, params)
    rescue service_class::PaymentError  => e
      return render status: 200, :json=> {:success => false, data: e.message }
    end
    return render status: 201, :json=> {:success => true, data: {data: "Subscription deactivated" } }

   end

  def update_card
    return render status: 200, :json=> {:success => false, data: [t('no_account')] } unless current_user.has_account?
    return render status: 200, :json=> {:success => false, data: [t('no_payment_gateway')] } if params[:payment_gateway_type].blank?
    service_class = payment_service
    return render status: 200, :json=> {:success => false, data: [t('invalid_payment_gateway')] } if service_class.nil?
    unless  method_exist?(service_class,:update_card_details_service )
      return render status: 200, :json=> {:success => false, data: [t('no_feature_for_this_service',
                                                                      service: service_class, method: 'update card')] }
    end
    begin
      #redirecting corresponding payment gateway service
      service_class = payment_service
      service_class.new.update_card_details_service(current_user, params)
    rescue service_class::PaymentError  => e
      return render status: 200, :json=> {:success => false, data: e.message }
    end
    return render status: 201, :json=> {:success => true, data: {data: "Card updated" } }
  end


  def webhook
    begin
      StripePaymentService.new.webhook_service(request.body.read)
      #redirecting corresponding payment gateway service
      #service_class = payment_service
      #service_class.new.webhook_service(request.body.read)
    rescue service_class::PaymentError  => e
      return render status: 200, :json=> {:success => false, data: e.message }
    end
    return render status: 200, :json=> {:success => true, data: 'Success' }
  end


  def plan_with_name
    SubscriptionPlan.subscription_with_name(params[:subscription_type]).first
  end

  def get_subscription_type
    return render status: 200, :json=> {:success => false, data: [t('no_payment_gateway')] } if params[:payment_gateway_type].blank?
    service_class = payment_service
    return render status: 200, :json=> {:success => false, data: [t('invalid_payment_gateway')] } if service_class.nil?
    unless  method_exist?(service_class,:subscription_type_service )
      return render status: 200, :json=> {:success => false, data: [t('no_feature_for_this_service',
                                            service: service_class, method: 'get subscription type')] }
    end
    begin
      subscrition_types = service_class.new.subscription_type_service
    rescue service_class::PaymentError  => e
      return render status: 200, :json=> {:success => false, data: e.message }
    end
    return render status: 200, :json=> {:success => true, data: subscrition_types }
  end


  def subscription_status
      status = current_user.has_account? ? current_user.active_subscription? ? 'active' : 'canceled' : 'no_account'
      return render status: 200, :json=> {:success => true, data: {subscription_status: status } }
  end

  def method_exist? service_class, method_name
    service_class.instance_methods(false).include?(method_name)
  end

end

app/controllers/transactions_controller.rb
class  TransactionsController < ApplicationController
  include TransactionCommonMethodControllerConcern
  skip_before_filter :is_device_id?, :only => [:new,  :new_subscription, :change_card_details, :update_card_details, :create,:paypal_hook]
  skip_before_filter :authenticate_scope!, :only => [:new, :new_subscription, :change_card_details, :update_card_details, :create, :paypal_hook]
  skip_before_filter :authenticate_user_from_token!, :only => [:new, :new_subscription, :change_card_details, :update_card_details, :create, :paypal_hook]
  skip_before_filter :authenticate_device, :only => [:new, :new_subscription, :change_card_details, :update_card_details, :create, :paypal_hook]
  before_filter :authenticate_user!, :only => [:new]
  before_filter :reset_flash_message, :only => [:create, :update_card_details]
  before_filter :authenticate_user!, :except => [:paypal_hook]
  #force_ssl if: :ssl_configured?
  respond_to :json

  def new
    @user = current_user if current_user
    if @user.active_subscription?
      render template: 'transactions/paid_user'
    else
       initialize_transaction @user
    end
  end

  def new_subscription
    @user = User.find_by_subscription_token(params[:subscription_token])
    unless @user
      return render status: 200, :json=> {:success => false, data: 'Invalid Token' }
    end
    sign_in @user
    if @user.active_subscription?
      render template: 'transactions/paid_user'
    else
      initialize_transaction @user
      render "new"
    end
  end

  def initialize_transaction user
    @auth_token = user.authentication_token
    @user_type = user.user_type
    if params[:payment_error]
      @subscription_type = params[:subscription_type]
      @amount = params[:amount]
      @payment_gateway_type = params[:payment_gateway_type]
    else
      @plan = SubscriptionPlan.where('name !=?', 'Beta').order("id DESC")
    end
  end

  def change_card_details
    @user = current_user if current_user
  end

  def update_card_details
    no_account?
    is_payment_gateway?
    unless flash[:message].blank?
      redirect_to :back
    else
      begin
          service_class = payment_service
          service_class.new.update_card_details_service(current_user, params)
      rescue service_class::PaymentError  => e
        flash[:message] =  e.message
        return redirect_to :back
      end
    render template: 'transactions/show'
    end
  end

  def create
    is_already_active?
    is_type_mismatch?
    is_payment_gateway?
    is_invalid_plan?
    unless flash[:message].blank?
      return redirect_to new_transaction_path(payment_error: true, payment_gateway_type: params[:payment_gateway_type], subscription_type:params[:subscription_type], amount: params[:amount] )
    else
      begin
        service_class = payment_service
        if service_class == PaypalPaymentService
          create_payment_by_paypal
        else
          service_class.new.create_payment_service(current_user, params)
          #after Creating Payment
          sign_out current_user
          redirect_to ENV['AFTER_SUBSCRIPTION_URL']
        end
      rescue service_class::PaymentError  => e
          flash[:message] =  e.message
          return redirect_to new_transaction_path(payment_error: true, payment_gateway_type: params[:payment_gateway_type], subscription_type:params[:subscription_type], amount: params[:amount] )
      end
    end
  end

  def create_payment_by_paypal
    @paypal_purchase = PaypalPurchase.new
    @paypal_purchase = PaypalPurchase.create(user_id: current_user.id, duration: params[:subscription_type])
    redirect_to @paypal_purchase.paypal_url(params, ENV['AFTER_SUBSCRIPTION_URL'])
  end

  def paypal_hook
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    puts 'inside paypal hooks'
    if status == "Completed"
      puts 'complted status'
      @paypal_purchase = PaypalPurchase.where(token: params[:invoice]).first
      @paypal_purchase.save_with_paypal_payment(params) unless @paypal_purchase.nil?
    end
    puts "satus name" + status.to_s
    render nothing: true
  end

  def is_payment_gateway?
    if params[:payment_gateway_type].blank?
      flash[:message] =t('no_payment_gateway')
    elsif payment_service.nil?
      flash[:message] =t('invalid_payment_gateway')
    end
  end


  def no_account?
    flash[:message] =t('no_account') unless current_user.has_account?
  end

  def is_already_active?
    flash[:message] =t('active_subscription') if current_user.has_account? && current_user.active_subscription?
  end

  def is_type_mismatch?
    flash[:message] =t('user_type_mismatch') if current_user.user_type != params[:user_type]
  end

  def is_invalid_plan?
    plan = SubscriptionPlan.subscription_with_name(params[:subscription_type]).first
    flash[:message] =t('invalid_plan') if plan.nil?
  end

  def reset_flash_message
    flash[:message] = ''
  end

end

app/views/transactions/_payment_form.html.erb
<div class="rkv_wrapper" id = 'payment_form' style = 'display: none'>
  <div class="rkv_form_wrapper rkv_checkout">
    <h1>Checkout</h1>
    <div class="rkv_col2">
     <%= render partial: 'transactions/paypal_payment_form' %>
      <div class="rkv_form_container">
        <div class="rkv_form">
          <img src="/assets/secure-payments-powered-by-stripe.gif"style="width: 100%;">
          <%= form_tag subscripe_transactions_path, method:'post', class:'form-horizontal', id: 'subscription_payment_form' do %>
              <%= hidden_field_tag :user_type, @user_type %>
              <%= hidden_field_tag :card_id %>
              <%= hidden_field_tag :auth_token, @auth_token%>
              <%= hidden_field_tag :subscription_type, @subscription_type%>
              <%= hidden_field_tag :amount, @amount%>
              <%= hidden_field_tag :payment_gateway_type, @payment_gateway_type || 'Stripe'%>

              <div id="payment_error">
                <div class="message">
                  <%= flash[:message] %>
                  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
                </div>
              </div>
              <div id="payment_type_div">
                <%= render partial: 'transactions/stripe_payment_form' %>
             </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="rkv_col2">
      <div class="rkv_subscription_table">
        <div class="rkv_items_list_container">
          <ul>
            <li><span class ='rkv_susbcription_title'></span> <span class="rkv_price"></span></li>
          </ul>
        </div>
        <div class="rkv_total_price">
          <div class="total_text_label">Total:</div>
          <div class="rkv_total_amount"></div>
        </div>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.6/fastclick.js"></script>
<script type="text/javascript">
</script>
<style type="text/css">
  #paypal_transaction{
    display: none;
  }
</style>

app/views/transactions/_paypal_payment_form.html.erb
<%= form_tag subscripe_transactions_path, method:'post', class:'form-horizontal', id: 'paypal_payment_form' do %>
    <%= hidden_field_tag :user_type, @user_type %>
    <%= hidden_field_tag :auth_token, @auth_token%>
    <%= hidden_field_tag :subscription_type, @subscription_type%>
    <%= hidden_field_tag :amount, @amount%>
    <%= hidden_field_tag :payment_gateway_type, @payment_gateway_type || 'Paypal'%>
    <div class="rkv_row">
        <%= button_tag(type: 'submit', class: "submit-button payment-btn paypal_payment-btn pay_with_paypal") do %>
            <span class=''></span>
        <% end %>
    </div>

<%end%>

app/views/transactions/_stripe_payment_form.html.erb
<div id = 'stripe_payment_div'>
  <div class="rkv_row">
    <%= text_field_tag :f_name, @user.f_name, placeholder:"First Name"%>
  </div>
  <div class="rkv_row">
    <%= text_field_tag :l_name, @user.l_name, placeholder:"First Name"%>
  </div>
  <div class="rkv_row">
    <%= text_field_tag :card_number, nil, name: nil, placeholder: "Credit Card #", required: true%>
  </div>
  <div class="rkv_row" style="margin: 6px 0 26px">
    <label class="rkv_field_title" style="margin-right: 11px; line-height: 45px; text-indent: 15px;">Expiration Date</label>
    <div class="rkv_select_container wide">
      <%= select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month", class: 'rkv_select'}%>
      <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", class: 'rkv_select'}%>
      <%= text_field_tag :card_code, nil, name: nil,  placeholder: "CVV", style:"width:100px; padding:5px; border:1px solid #999; line-height:33px;", required: true %>
    </div>
  </div>
  <div class="rkv_row">
    <%= button_tag(type: 'submit' , class: "rkv_button submit-button payment-btn stripe_payment-btn") do %>
        <span >Continue</span>
    <% end %>
  </div>
</div>

app/views/transactions/change_card_details.html.erb
<div class="rkv_wrapper">
  <div class="rkv_form_wrapper  rkv_checkout">
    <h1>Update Card Details</h1>
    <div class="rkv_col2">
      <div class="rkv_form_container">
        <div class="rkv_form">
          <%= form_tag update_card_transactions_path, method:'put', class:'form-horizontal', id: 'subscription_payment_form' do %>
              <%= hidden_field_tag :card_id %>
              <%= hidden_field_tag :payment_gateway_type, @payment_gateway_type || 'stripe'%>
              <div id="payment_error">
                <div class="message">
                  <%= flash[:message] %>
                  <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
                </div>
              </div>
              <div id="payment_type_div">
                <%= render partial: 'transactions/stripe_payment_form' %>
              </div>
          <%end%>
        </div>
      </div>
    </div>

  </div>
</div>

<style type="text/css">
    body {
        background-image: none;
    }
</style>

<%= javascript_include_tag "transactions" %>
<%= javascript_include_tag "stripe" %>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.6/fastclick.js"></script>

app/views/transactions/new.html.erb
<div class="rkv_wrapper" id = 'plan_select_form'>
  <div class="rkv_section rkv_video_section">

    <h2 class="rkv_headding">
      Unlock the Nuryl Playlist
    </h2>
      <div class="rkv_col2">
        <div class="rkv_video_container">
          <iframe src="https://player.vimeo.com/video/158950941" width="500" height="286" frameborder="0" title="Nuryl How-To 2.0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
      </div>

      <div class="rkv_col2">
        <ul class="rkv_list_items">
          <li>Get a New Playlist Every Month Specifically Designed Specifically for Your Baby's Date of Birth</li>
          <li>29 Playlists, Nearly 600 Musical Pieces</li>
          <li>HALF of the Nuryl Playlists Are Comprised of Pieces That Were Created ONLY for Nuryl and Can't Be Found Anywhere</li>
          <li>Mini Music Lessons Built-in to the Playlists</li>
          <li>Track Your Baby's Daily, Weekly, and Monthly Listening</li>
        </ul>
      </div>
  </div>
  <div class="rkv_section rkv_offers_section">
    <h1 class="rkv_headding">Choose Your Plan Now</h1>
    <div class="rkv_services_container">
      <%unless @plan.nil?%>
       <%@plan.each do |plan|%>
          <div class="rkv_col3">
            <%if plan.name == 'Yearly'%>  <div class="rkv_offer_text"><span>Most Popular</span></div> <%end%>
            <h2 class="rkv_plan_name"><%=plan.display_name%></h2>
            <%if plan.name == 'Yearly' || plan.name == 'Gift'%>
                <p class="rkv_plan_price"><span class="rkv_old_price">$119.88</span><span class="nuryl_price rkv_new_price"><%=plan.amount%></span></p>
            <%else%>
            <p class="rkv_plan_price"><span class="rkv_price nuryl_price"><%=plan.amount%>
            <%end%>
            <%if plan.name == 'Monthly'%>/<sub>Month</sub>
            </span></p>
            <p class="rkv_plan_details">Subscribe to Nuryl with a monthly plan and have full access to the entire catalog of playlists.</p>

            <%elsif plan.name == 'Yearly'%>
                <p class="rkv_plan_details">Subscribe for a full year and save big! Unlock the playlists now.</p>

            <%elsif plan.name == 'Gift'%>
                <p class="rkv_plan_details">Give the gift of Nuryl to a family member of friend. Nuryl is a gift that will last a lifetime.</p>
            <%end%>
            <a href="#" class="rkv_choose_plan rkv_button">Choose Plan</a>
          </div>
       <%end%>
      <%end%>
    </div>
  </div>
</div>
<%= render partial: 'transactions/payment_form' %>


<%= javascript_include_tag "transactions" %>
<%= javascript_include_tag "stripe" %>
<%= javascript_include_tag "paypal" %>



<style type="text/css">
    header.rkv-header {
        url('/assets/header-background.jpg');
    }
    body {
        background-image: none;
    }
</style>


<script type="text/javascript">
    //mix panel show page tracking
    mixpanel.identify(distinct_id);
    mixpanel.people.set({});
    mixpanel.track(
            "W choose plan show"
    );

</script>

app/views/transactions/paid_user.html.erb
<div class="rkv_wrapper">
  <div class="rkv_form_wrapper  rkv_checkout">
    <h1>Your subscription is active. For listening songs, please login to app.</h1>
  </div>
</div>

<style type="text/css">
    body {
        background-image: none;
    }
</style>

app/views/transactions/show.html.erb
<div class="rkv_wrapper">
  <div class="rkv_form_wrapper  rkv_checkout">
    <h1>Card Details Updated</h1>
   </div>
 </div>

<style type="text/css">
    body {
        background-image: none;
    }
</style>