config/routes.rb
require 'api_constraints'
Nuryl::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,path_names: {sign_up: "registrations"} ,controllers: {sessions: 'sessions', passwords: 'passwords'}
  resources :users, only: [:show, :edit, :update ]
  # Api definition
  devise_scope :user do
    root to: "sessions#new"
    match 'api/v1/user_registration' => 'api/v1/registrations#create', :via => :post
    match 'api/v1/help' => 'api/v1/helps#create', :via => :post
    match '/api/v1/users/forget_password' => 'api/v1/passwords#create', :via => :post
    match '/api/v1/users/change_password' => 'api/v1/passwords#update_password_api', :via => :put
    match 'user_registration' => 'api/v1/registrations#new', :via => :get
    match 'registration' => 'registrations#create', :via => :post
    match  'subscribe' => 'transactions#new_subscription', :via => :get
    match 'edit_password' => 'devise/passwords#edit', :via => :get
    match 'update_password/:id' => 'devise/passwords#update', :via => :put
  end


  namespace :api, defaults: { format: :json },
             path: '/api'  do
    scope module: :v1 , path: '/v1',
          constraints: ApiConstraints.new(version: 1, default: true) do
      # We are going to list our resources here
      devise_for :users
      resources :users ,only: [] do
        collection do
          get 'course_content'
          get 'validate_unique_email'
          get 'courses/:course_id/:content_type/:content_id' => 'users#get_content'
          post 'courses/:course_id' => 'users#player_usage_status'
          get 'usage_statics' => 'users#send_usage_statics_info'
          get 'edit_profile' => 'users#edit_profile'
          post 'update_profile' => 'users#update_profile'
          get 'subscription_mail' => 'users#send_subscription_mail'
          get 'get_urls' => 'users#get_urls'
        end
      end
      resources :transactions, only: [:create] do
        collection do
          post 'subscripe' => 'transactions#create'
          get 'subscription_type' => 'transactions#get_subscription_type'
          get 'subscription_status' => 'transactions#subscription_status'
          get 'subscription_amount' => 'transactions#get_subscription_amount'
          post 'change_subscription_plan' => 'transactions#change_plan'
          post 'new_subscription' => 'transactions#new_subscription'
          post 'cancel_subscription' => 'transactions#cancel_subscription'
          post 'webhook' => 'transactions#webhook'
          put 'update_card' => 'transactions#update_card'
        end
      end
    end
  end

  resources :transactions ,only: [:new] do
    collection do
      get 'change_card_details' => 'transactions#change_card_details'
      put 'update_card' => 'transactions#update_card_details'
      post 'paypal_transaction_process' => 'transactions#paypal_transaction_process'
      post 'subscripe' => 'transactions#create'
      post 'paypal_hook' => 'transactions#paypal_hook'
    end
  end



  resources :childrens ,only: [:new, :create] do

  end


end

app/views/layouts/_footer.html.erb
<iframe src="https://www.nuryl.com/footer-iframe/" style="border:0px #FFFFFF none;" name="myiFrame" scrolling="no" frameborder="0" marginheight="0px" marginwidth="0px" height="%" width="100%"></iframe>

app/views/layouts/_header.html.erb
<header class="rkv-header">
  <div class="rkv-search-bar">
    <div class="rkv_wrapper">
      <form>
        <div class="rkv-input-wrapper">
          <input type="text" placeholder="search">
          <div class="rkv-close-btn"></div>
        </div>
      </form>
    </div>
  </div>
  <div class="rkv-menu-bar">
    <div class="rkv_wrapper">
      <div class="rkv-logo-section">
        <a href="https://nuryl.com">
          <img class="rkv-logo1" src="/assets/logo.png">
          <img class="rkv-logo2" src="/assets/logo-2.png">
        </a>
      </div>
      <div class="rkv-responsive-search-button"></div>
      <div class="rkv-responsive-menu-button"></div>
      <div class="rkv-menu-section">

        <% header_tabs = HTTParty.get('https://www.nuryl.com/wp-json/wp-api-menus/v2/menu-locations/main_navigation') %>
        <ul>
          <% header_tabs.each do |header| %>
            <% if header["children"].present? %>
              <li>
                <div class="dropdown">
                  <%= button_to "#{header["title"]}", header["url"],{class:"dropbtn"}%>
                  <div class="dropdown-content">
                    <ul class="sub-menu">
                      <% header["children"].each do |clild| %>
                        <li><a href="<%= clild["url"]%>"><%= clild["title"] %></a></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </li>
            <% else %>
              <li><a href="<%= header["url"]%>"  class=""><%= header["title"]%></a></li>
            <% end %>
          <% end %>
          <% if user_signed_in? %>
            <li>
              <div class="dropdown">
                <%= button_to "Hi #{current_user.f_name}","#",{class:"dropbtn"}%>
                <div class="dropdown-content">
                  <ul class="sub-menu">
                    <li>
                        <%if current_user.account_type("STRIPE") %>
                            <%= link_to '<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <span class="mrg-left-3">Update Card</span><i class="icon-arrow-right"></i>'.html_safe, change_card_details_transactions_path %>
                        <%end%>
                    </li>
                    <li><a href="<%= edit_user_path(current_user) %>">Edit Account</a></li>
                    <li><a href="<%= user_path(current_user) %>">Account</a></li>
                    <li><%= button_to "Log out", destroy_user_session_path,{method: :delete,class:"hidden-menu logout"}%></a></li>
                  </ul>
                </div>
              </div>
            </li>
          <%end%><!-- 
          <li><a href="http://www.nuryl.com" class="rkv-search"></a></li> -->
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nuryl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= tag :meta, :name => "mix_panel_token", :content => ENV['MIX_PANEL_TOKEN'] %>
  <%= tag :meta, :name => "distinct_id", :content => user_signed_in? ? current_user.email: '' %>


  <!-- start Mixpanel -->
    <script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
        0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
    for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
    mixpanel.init($('meta[name="mix_panel_token"]').attr('content'), {
        loaded: function() {
            window.distinct_id = $('meta[name="distinct_id"]').attr('content')
        }
    });

    </script>
  <!-- end Mixpanel -->



  <%= csrf_meta_tags %>
</head>

<!-- Page Wrapper START-->




<body>
<%= render partial: 'layouts/header' %>

<%= yield %>
<%= render partial: 'layouts/footer' %>

</body>
</html>